# yaml-language-server: $schema=../../schema/config.schema.json
libraries:
  - name: example
    type: artifactory
    path: ${ARTIFACTORY_API_PATH}
    artifactory:
      url: ${ARTIFACTORY_API_URL}
      repo: ${ARTIFACTORY_API_REPO}
      auth:
        api_key: ${ARTIFACTORY_API_KEY}

logging:
  format: standard
  level: info
