---
name: Generate vSphere Content Library

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: make build
      - name: Generate Content Library Metadata
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_REPOSITORY: ${{ secrets.ARTIFACTORY_REPOSITORY }}
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          ./bin/artifactory-content-library generate --config example/workflows/artifactory-config.yml
