# yaml-language-server: $schema=https://raw.githubusercontent.com/tenthirtyam/artifactory-content-library/main/schema/config.schema.json
---
vsphere:
  url: ${VSPHERE_URL}
  username: ${VSPHERE_USERNAME}
  password: ${VSPHERE_PASSWORD}
  ssl_verify: true

library:
  name: Artifactory Subscribed Library
  datacenter: dc01
  datastore: ds01
  auto_sync: true
  on_demand: false
  publisher_subscription_url: https://packages.example.com/artifactory/.../lib.json
  publisher_ssl_thumbprint: ""
  publisher_username: ${VSPHERE_PUBLISHER_USERNAME}
  publisher_password: ${VSPHERE_PUBLISHER_PASSWORD}

logging:
  format: standard
  level: info
