# yaml-language-server: $schema=https://raw.githubusercontent.com/tenthirtyam/artifactory-content-library/main/schema/config.schema.json
---
libraries:
  - name: example
    type: artifactory
    path: path/to/content
    artifactory:
      url: https://packages.example.com/artifactory
      repo: example
      ssl_verify: true
      rate_limit: 10
      timeout_seconds: 30
      max_retries: 3
      auth:
        # Use Basic Authentication:
        # username: ${ARTIFACTORY_USERNAME}
        # password: ${ARTIFACTORY_PASSWORD}
        # Or Use API Key:
        # api_key: ${ARTIFACTORY_API_KEY}
        # Or Use Access Token:
        # token: ${ARTIFACTORY_TOKEN}

logging:
  format: standard
  level: info
